Added TypeScript typings
auth0/idtoken-verifier pull request #122
Opened 2021-05-05 03:46 UTC by ItalyPaleAle

### Changes

This PR adds TypeScript definitions for the library. This was auto-generated from JSDoc, but with some manual fixes applied.

### Testing

N/A

### Checklist

- [X] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [X] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
- [X] All existing and new tests complete without errors

2021-05-18 10:36 UTC, stevehobbsdev requested changes
Looks good, thanks for the contribution! Just a couple of changes needed.

2021-05-18 10:36 UTC, stevehobbsdev commented on types/index.d.ts
> +  verify(token: string, requestedNonce: any, cb: verifyCallback): any;
I think we can type `requestedNonce` as `string` here.

2021-05-18 10:36 UTC, stevehobbsdev commented on types/index.d.ts
> +  getRsaVerifier(iss: any, kid: any, cb: any): void;
Let's remove this, it's not part of the public documented API.

2021-06-10 04:10 UTC, ItalyPaleAle commented
@stevehobbsdev Sorry for the delay. Updates as requested

2021-06-15 15:17 UTC, fnagel commented
@stevehobbsdev Any chance to get this merged soon? :-)

2021-06-16 09:21 UTC, stevehobbsdev commented
@fnagel Yes - let me put out a release this week 👍🏻

2021-06-17 08:01 UTC, fnagel commented
@stevehobbsdev Wonderful :-) Thanks a lot!

2021-06-18 10:32 UTC, stevehobbsdev approved these changes

2021-06-18 10:33 UTC, merged